"""7-day paper experiment report generation."""
from __future__ import annotations

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db import models
from app.services.analytics.metrics import compute_metrics


async def generate_experiment_report(
    db: AsyncSession,
    experiment: models.PaperExperiment,
) -> dict[str, Any]:
    port_result = await db.execute(select(models.Portfolio).limit(1))
    portfolio = port_result.scalar_one_or_none()
    metrics = await compute_metrics(db, portfolio.id) if portfolio else {}

    trades_result = await db.execute(
        select(models.Trade).where(models.Trade.is_backtest == False).order_by(models.Trade.closed_at)  # noqa: E712
    )
    trades = list(trades_result.scalars().all())

    signals_result = await db.execute(
        select(models.Signal).order_by(models.Signal.created_at)
    )
    signals = list(signals_result.scalars().all())
    acted = [s for s in signals if s.acted_on]
    missed = [s for s in signals if not s.acted_on and s.signal_type in ("BUY", "SELL", "EXIT")]

    snaps = await db.execute(
        select(models.EquitySnapshot)
        .where(models.EquitySnapshot.portfolio_id == portfolio.id)
        .order_by(models.EquitySnapshot.created_at)
    )
    equity_curve = [
        {"ts": s.created_at.isoformat(), "equity": s.equity}
        for s in snaps.scalars().all()
    ]

    total_slippage = sum(t.slippage for t in trades)
    total_charges = sum(t.brokerage + t.charges for t in trades)
    gross = sum(t.gross_pnl for t in trades)
    net = sum(t.net_pnl for t in trades)

    starting = experiment.starting_capital
    ending = portfolio.equity if portfolio else starting
    ret = ((ending - starting) / starting * 100) if starting else 0

    return {
        "title": "7-DAY STRATEGY REPORT",
        "experiment": experiment.name,
        "strategy": experiment.strategy_name,
        "symbols": experiment.symbols,
        "timeframe": experiment.timeframe,
        "started_at": experiment.started_at.isoformat() if experiment.started_at else None,
        "ended_at": experiment.ends_at.isoformat() if experiment.ends_at else None,
        "starting_capital": starting,
        "ending_capital": round(ending, 2),
        "net_pnl": round(ending - starting, 2),
        "return_pct": round(ret, 4),
        "strategy_performance": {
            **metrics,
            "note": "Based on closed paper trades generated by strategy signals.",
        },
        "simulated_execution_performance": {
            "gross_pnl": round(gross, 2),
            "net_pnl": round(net, 2),
            "slippage_impact": round(total_slippage, 2),
            "transaction_cost_impact": round(total_charges, 2),
            "execution_drag": round(gross - net, 2),
            "disclaimer": (
                "Simulated P&L is NOT identical to actual broker P&L. "
                "Uses market data + configurable slippage/charges assumptions."
            ),
        },
        "signal_accuracy": {
            "total_signals": len(signals),
            "acted_on": len(acted),
            "signals_without_trades": len(missed),
            "missed_or_rejected": [
                {
                    "symbol": s.symbol,
                    "type": s.signal_type,
                    "reason": s.rejection_reason or s.reason,
                    "ts": s.created_at.isoformat() if s.created_at else None,
                }
                for s in missed[-50:]
            ],
        },
        "equity_curve": equity_curve[-500:],
        "trades": [
            {
                "symbol": t.symbol,
                "side": t.side,
                "entry": t.entry_price,
                "exit": t.exit_price,
                "qty": t.quantity,
                "net_pnl": t.net_pnl,
                "gross_pnl": t.gross_pnl,
                "reason_entry": t.entry_reason,
                "reason_exit": t.exit_reason,
                "opened_at": t.opened_at.isoformat() if t.opened_at else None,
                "closed_at": t.closed_at.isoformat() if t.closed_at else None,
            }
            for t in trades
        ],
        "disclaimer": (
            "Paper trading results do not guarantee live trading results. "
            "LIVE MODE remains disabled until manual human review."
        ),
    }
